apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-myip
spec:
  selector:
    matchLabels:
      app: echo-hostname
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: echo-hostname
    spec:
      containers:
      - name: myip
        image: aaronbolton78/myip:latest
        ports:
        - containerPort: 80
